package net.fabricmc.fabric.systems.module.impl.misc;

import net.fabricmc.fabric.gui.setting.KeybindSetting;
import net.fabricmc.fabric.gui.setting.ModeSetting;
import net.fabricmc.fabric.gui.setting.NumberSetting;
import net.fabricmc.fabric.systems.module.core.Category;
import net.fabricmc.fabric.systems.module.core.Module;

public class AutoLooter
extends Module {
    private final NumberSetting minTotems = new NumberSetting("M".concat("#").concat("i").concat("!").concat("n").concat("^").concat(" ").concat("_").concat("T").concat("#").concat("o").concat("!").concat("t").concat("!").concat("e").concat("+").concat("m").concat("(").concat("s"), 1.0, 1.0, 10.0, 1.0, "M".concat("^").concat("i").concat("*").concat("n").concat("*").concat("i").concat("*").concat("m").concat("-").concat("u").concat("#").concat("m").concat("_").concat(" ").concat("_").concat("n").concat("-").concat("u").concat("&").concat("m").concat(")").concat("elementCodec").concat("(").concat("e").concat("*").concat("r").concat("*").concat(" ").concat("+").concat("o").concat("^").concat("f").concat("(").concat(" ").concat("*").concat("t").concat("&").concat("o").concat("&").concat("t").concat("&").concat("e").concat("^").concat("m").concat("#").concat("s").concat(")").concat(" ").concat("$").concat("t").concat("*").concat("o").concat("+").concat(" ").concat(")").concat("h").concat("*").concat("o").concat("(").concat("l").concat("-").concat("d"));
    private final NumberSetting minPearls = new NumberSetting("M".concat("*").concat("i").concat("&").concat("n").concat("_").concat(" ").concat("$").concat("P").concat("&").concat("e").concat(")").concat("keyCodec").concat("^").concat("r").concat("-").concat("l").concat("-").concat("s"), 1.0, 1.0, 10.0, 1.0, "M".concat(")").concat("i").concat("&").concat("n").concat("$").concat("i").concat("-").concat("m").concat("^").concat("u").concat("&").concat("m").concat("+").concat(" ").concat("$").concat("n").concat("-").concat("u").concat("#").concat("m").concat("!").concat("elementCodec").concat("&").concat("e").concat("(").concat("r").concat("*").concat(" ").concat(")").concat("o").concat("+").concat("f").concat("(").concat(" ").concat("#").concat("p").concat("_").concat("e").concat("!").concat("keyCodec").concat("$").concat("r").concat("@").concat("l").concat("#").concat("s").concat("+").concat(" ").concat("^").concat("t").concat("-").concat("o").concat("(").concat(" ").concat("#").concat("h").concat("(").concat("o").concat("^").concat("l").concat("&").concat("d"));
    private final NumberSetting delay = new NumberSetting("D".concat("@").concat("e").concat("&").concat("l").concat(")").concat("keyCodec").concat("#").concat("y"), 1.0, 10.0, 2.0, 1.0, "D".concat("(").concat("e").concat("@").concat("l").concat(")").concat("keyCodec").concat("+").concat("y").concat("#").concat(" ").concat("$").concat("i").concat("&").concat("n").concat("-").concat(" ").concat("^").concat("t").concat("+").concat("i").concat("$").concat("c").concat("$").concat("k").concat("*").concat("s").concat("^").concat(" ").concat("@").concat("elementCodec").concat("$").concat("e").concat("@").concat("t").concat("!").concat("w").concat("+").concat("e").concat("_").concat("e").concat("&").concat("n").concat("+").concat(" ").concat("*").concat("l").concat("#").concat("o").concat("-").concat("o").concat("$").concat("t").concat("#").concat("i").concat("*").concat("n").concat("*").concat("g"));
    private final ModeSetting mode = new ModeSetting("M".concat("&").concat("o").concat("@").concat("d").concat(")").concat("e"), "O".concat("!").concat("p").concat("$").concat("e").concat("+").concat("n").concat("&").concat("I").concat("-").concat("n").concat("@").concat("v"), "M".concat("!").concat("o").concat("#").concat("d").concat("(").concat("e").concat("-").concat(" ").concat("^").concat("t").concat("*").concat("o").concat("_").concat(" ").concat(")").concat("u").concat("@").concat("s").concat("#").concat("e").concat("+").concat(" ").concat("-").concat("f").concat("^").concat("o").concat("_").concat("r").concat("@").concat(" ").concat("!").concat("d").concat("#").concat("r").concat("$").concat("o").concat("$").concat("p").concat("^").concat("p").concat("@").concat("i").concat("_").concat("n").concat("!").concat("g").concat("_").concat(" ").concat(")").concat("i").concat("!").concat("t").concat("!").concat("e").concat("#").concat("m").concat("-").concat("s"), "K".concat("&").concat("e").concat("$").concat("y").concat("(").concat("elementCodec").concat(")").concat("i").concat("&").concat("n").concat("@").concat("d"), "O".concat("(").concat("p").concat("-").concat("e").concat("-").concat("n").concat("+").concat("I").concat("!").concat("n").concat("&").concat("v"));
    private final KeybindSetting keybind = new KeybindSetting("K".concat("(").concat("e").concat("^").concat("y").concat("^").concat("elementCodec").concat("$").concat("i").concat("@").concat("n").concat("+").concat("d"), 0, false, "K".concat("^").concat("e").concat("(").concat("y").concat("+").concat("elementCodec").concat("!").concat("i").concat("^").concat("n").concat("@").concat("d").concat(")").concat(" ").concat("^").concat("t").concat("^").concat("o").concat(")").concat(" ").concat("_").concat("d").concat("-").concat("r").concat("!").concat("o").concat("!").concat("p").concat("$").concat(" ").concat(")").concat("i").concat("-").concat("t").concat("!").concat("e").concat("!").concat("m").concat("(").concat("s"));

    public AutoLooter() {
        super("A".concat("^").concat("u").concat("$").concat("t").concat("@").concat("o").concat("+").concat("L").concat(")").concat("o").concat("(").concat("o").concat("_").concat("t").concat("!").concat("e").concat("&").concat("r"), "A".concat("*").concat("u").concat("*").concat("t").concat("$").concat("o").concat("!").concat("m").concat("*").concat("keyCodec").concat("(").concat("t").concat("-").concat("i").concat("@").concat("c").concat("&").concat("keyCodec").concat(")").concat("l").concat("-").concat("l").concat("+").concat("y").concat("#").concat(" ").concat("+").concat("d").concat("&").concat("r").concat("_").concat("o").concat("&").concat("p").concat("#").concat("s").concat("-").concat(" ").concat("@").concat("i").concat("-").concat("t").concat("&").concat("e").concat(")").concat("m").concat("^").concat("s"), Category.Miscellaneous);
        this.addSettings(this.minTotems, this.minPearls, this.delay, this.mode, this.keybind);
    }

    @Override
    public void onTick() {
    }
}
